/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fpt.edu.lab.view;

import fpt.edu.lab.dao.UserDao;
import fpt.edu.lab.model.User;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author Hi
 */
public class ChangePasswordJPanel extends javax.swing.JPanel {

    ResourceBundle bundle;
    User user;

    /**
     * Creates new form ChangePasswordJPanel
     * @param bundle
     */
    public ChangePasswordJPanel(ResourceBundle bundle, User user) {
        initComponents();
        this.bundle = bundle;
        this.user = user;
        setUpUILanguage();
    }

    public void setUpUILanguage() {
        jlbNewPassword.setText(bundle.getString("jlbNewPassword"));
        jlbOldPassword.setText(bundle.getString("jlbOldPassword"));
        jlbConfirmPassword.setText(bundle.getString("jlbConfirmPassword"));
        jbtnChangePassword.setText(bundle.getString("jbtnChangePassword"));
        jPanel1.setBorder(BorderFactory.createTitledBorder(bundle.getString("jlbChangePassword")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbConfirmPassword = new javax.swing.JLabel();
        jtfOldPassword = new javax.swing.JTextField();
        jtfNewPassword = new javax.swing.JTextField();
        jtfConfirmPassword = new javax.swing.JTextField();
        jbtnChangePassword = new javax.swing.JButton();
        jlbOldPassword = new javax.swing.JLabel();
        jlbNewPassword = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Change Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jlbConfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbConfirmPassword.setText("Confirm New Password");

        jtfOldPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfOldPassword.setPreferredSize(new java.awt.Dimension(250, 35));

        jtfNewPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfNewPassword.setPreferredSize(new java.awt.Dimension(250, 35));

        jtfConfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfConfirmPassword.setPreferredSize(new java.awt.Dimension(250, 35));

        jbtnChangePassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnChangePassword.setText("Change Password");
        jbtnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChangePasswordActionPerformed(evt);
            }
        });

        jlbOldPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbOldPassword.setText("Old Password");

        jlbNewPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbNewPassword.setText("New Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jtfOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jtfNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jtfConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jbtnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbOldPassword))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbNewPassword))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jlbConfirmPassword))
                    .addComponent(jtfConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChangePasswordActionPerformed
        String password = jtfOldPassword.getText();
        String passwordChange = jtfNewPassword.getText();
        String passwordConfirm = jtfConfirmPassword.getText();
        //kiểm tra passwordChange == passwordConfirm
        if (passwordChange.equals(passwordConfirm)) {
            if (UserDao.changePassword(passwordChange, password, user.getUsername()) == true) {
                JOptionPane.showMessageDialog(this, bundle.getString("joChangPassSuccess"));
            } else {
                JOptionPane.showMessageDialog(this, bundle.getString("joChangePassFail"));
            }
        } else {
            JOptionPane.showMessageDialog(this, bundle.getString("joSamePass"));
        }
    }//GEN-LAST:event_jbtnChangePasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnChangePassword;
    private javax.swing.JLabel jlbConfirmPassword;
    private javax.swing.JLabel jlbNewPassword;
    private javax.swing.JLabel jlbOldPassword;
    private javax.swing.JTextField jtfConfirmPassword;
    private javax.swing.JTextField jtfNewPassword;
    private javax.swing.JTextField jtfOldPassword;
    // End of variables declaration//GEN-END:variables
}
