/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fpt.edu.lab.view;

import fpt.edu.lab.dao.LanguageDAO;
import fpt.edu.lab.dao.UserDao;
import fpt.edu.lab.model.Language;
import fpt.edu.lab.model.User;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author Viet Long
 */
public class LoginJFrame extends javax.swing.JFrame {

    ResourceBundle bundle;

    /**
     * Creates new form LoginJFrame
     */
    public LoginJFrame() {
        initComponents();
        Language language = LanguageDAO.getLanguage();
        setUpUILanguage(language.getCode(), language.getCountry());
        setLocationRelativeTo(null);
        jlbMessage.setForeground(Color.red);
    }

    public void setUpUILanguage(String language, String country) {
        Locale lang = new Locale(language, country);
        bundle = ResourceBundle.getBundle("fpt.edu.lab.language.Content", lang);
        setTitle(bundle.getString("title"));
        jbtnLogin.setText(bundle.getString("jbtnLogin"));
        jlbTitle.setText(bundle.getString("jlbMinimart"));
        jlbUserName.setText(bundle.getString("jlbUserName"));
        jlbPassword.setText(bundle.getString("jlbPassword"));
        jlbMessage.setText(bundle.getString("jlbMessage"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpnLogin = new javax.swing.JPanel();
        jlbUserName = new javax.swing.JLabel();
        jtfUserName = new javax.swing.JTextField();
        jlbPassword = new javax.swing.JLabel();
        jpfPassword = new javax.swing.JPasswordField();
        jlbTitle = new javax.swing.JLabel();
        jbtnLogin = new javax.swing.JButton();
        jlbMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jpnLogin.setBackground(new java.awt.Color(255, 255, 255));
        jpnLogin.setPreferredSize(new java.awt.Dimension(361, 220));
        jpnLogin.setLayout(new java.awt.GridBagLayout());

        jlbUserName.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jlbUserName.setText("UserName");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jpnLogin.add(jlbUserName, gridBagConstraints);

        jtfUserName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtfUserName.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 15);
        jpnLogin.add(jtfUserName, gridBagConstraints);

        jlbPassword.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jlbPassword.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jpnLogin.add(jlbPassword, gridBagConstraints);

        jpfPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jpfPassword.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 15);
        jpnLogin.add(jpfPassword, gridBagConstraints);

        jlbTitle.setBackground(new java.awt.Color(255, 255, 255));
        jlbTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlbTitle.setForeground(new java.awt.Color(0, 102, 0));
        jlbTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fpt/edu/lab/images/logoLogin.png"))); // NOI18N
        jlbTitle.setText("MiniMart Management");
        jlbTitle.setOpaque(true);
        jlbTitle.setPreferredSize(new java.awt.Dimension(280, 48));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        jpnLogin.add(jlbTitle, gridBagConstraints);

        jbtnLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnLogin.setText("Login");
        jbtnLogin.setPreferredSize(new java.awt.Dimension(133, 30));
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jpnLogin.add(jbtnLogin, gridBagConstraints);

        jlbMessage.setBackground(new java.awt.Color(255, 0, 0));
        jlbMessage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbMessage.setText("Message");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jpnLogin.add(jlbMessage, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.ipady = 117;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jpnLogin, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        String userName = jtfUserName.getText();
        String password = new String(jpfPassword.getPassword());
        User user = UserDao.loginUser(userName, password);
        if (user != null) {
            MainJFrame main = new MainJFrame(user);
            main.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, bundle.getString("joWrongUsername"));
        }
    }//GEN-LAST:event_jbtnLoginActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JLabel jlbMessage;
    private javax.swing.JLabel jlbPassword;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JLabel jlbUserName;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JPanel jpnLogin;
    private javax.swing.JTextField jtfUserName;
    // End of variables declaration//GEN-END:variables
}
