/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fpt.edu.lab.view;

import fpt.edu.lab.model.ListBean;
import fpt.edu.lab.controller.MiniMartController;
import fpt.edu.lab.dao.LanguageDAO;
import fpt.edu.lab.model.Language;
import fpt.edu.lab.model.User;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author Viet Long
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     *
     * @param user
     */
    private User user;
    public MainJFrame(User user) {
        this.user = user;
        initComponents();
        setLocationRelativeTo(null);
        Language language = LanguageDAO.getLanguage();
//        setExtendedState(MAXIMIZED_BOTH);
        setSize(1300, 720);
        setUpUILanguage(language.getCode(), language.getCountry());
        loadPermission(user.getRolename());
    }
    
    private void a() {
        dispose();
    }

    public void loadPermission(String permision) {
        MiniMartController controller = new MiniMartController(jpnView, user);
        controller.setView(jpnMiniMart, jlbMinimart);
        List<ListBean> listItem = new ArrayList<>();
        switch (permision) {
            //Admin
            case "Admin":
                jpnBilling.setVisible(false);
                jpnInventory.setVisible(false);
                jpnMiniMart.setVisible(true);
                jpnMiniMart.setBackground(Color.red);
                listItem.add(new ListBean("HomePage", jpnHomePage, jlbHomePage));
                listItem.add(new ListBean("User", jpnUser, jlbUser));
                listItem.add(new ListBean("Product", jpnProduct, jlbProduct));
                listItem.add(new ListBean("ProductCategory", jpnProductCategory, jlbProductCategory));
                listItem.add(new ListBean("Reporting", jpnReporting, jlbReporting));
                listItem.add(new ListBean("Support", jpnSupport, jlbSupport));
                break;
            //seller
            case "Seller":
                jpnInventory.setVisible(false);
                jpnUser.setVisible(false);
                jpnProduct.setVisible(false);
                jpnProductCategory.setVisible(false);
                jpnReporting.setVisible(false);
                jpnSupport.setVisible(false);
                jpnMiniMart.setVisible(true);
                jpnMiniMart.setBackground(Color.red);
                listItem.add(new ListBean("HomePage", jpnHomePage, jlbHomePage));
                listItem.add(new ListBean("Billing", jpnBilling, jlbBilling));
                break;
            //staff
            case "Staff":
                jpnBilling.setVisible(false);
                jpnUser.setVisible(false);
                jpnProduct.setVisible(false);
                jpnProductCategory.setVisible(false);
                jpnReporting.setVisible(false);
                jpnSupport.setVisible(false);
                jpnMiniMart.setVisible(true);
                jpnMiniMart.setBackground(Color.red);
                listItem.add(new ListBean("HomePage", jpnHomePage, jlbHomePage));
                listItem.add(new ListBean("Inventory", jpnInventory, jlbInventory));
                break;
            default:
                break;
        }
        listItem.add(new ListBean("ChangePassword", jpnChangePassword, jlbChangePassword));
        controller.setEvent(listItem);
    }

    public void setUpUILanguage(String language, String country) {
        ResourceBundle bundle;
        Locale lang = new Locale(language, country);
        bundle = ResourceBundle.getBundle("fpt.edu.lab.language.Content", lang);
        setTitle(bundle.getString("title"));
        jlbMinimart.setText(bundle.getString("jlbMinimart"));
        jlbHomePage.setText(bundle.getString("jlbHomePage"));
        jlbUser.setText(bundle.getString("jlbUser"));
        jlbProduct.setText(bundle.getString("jlbProduct"));
        jlbInventory.setText(bundle.getString("jlbInventory"));
        jlbProductCategory.setText(bundle.getString("jlbProductCategory"));
        jlbBilling.setText(bundle.getString("jlbBilling"));
        jlbReporting.setText(bundle.getString("jlbReporting"));
        jlbSupport.setText(bundle.getString("jlbSupport"));
        jlbChangePassword.setText(bundle.getString("jlbChangePassword"));
        jbtnLogOut.setText(bundle.getString("jbtnLogOut"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpnView = new javax.swing.JPanel();
        jpnRoot = new javax.swing.JPanel();
        jpnMenu = new javax.swing.JPanel();
        jpnMiniMart = new javax.swing.JPanel();
        jlbMinimart = new javax.swing.JLabel();
        jpnUser = new javax.swing.JPanel();
        jlbUser = new javax.swing.JLabel();
        jpnProduct = new javax.swing.JPanel();
        jlbProduct = new javax.swing.JLabel();
        jpnInventory = new javax.swing.JPanel();
        jlbInventory = new javax.swing.JLabel();
        jpnProductCategory = new javax.swing.JPanel();
        jlbProductCategory = new javax.swing.JLabel();
        jpnBilling = new javax.swing.JPanel();
        jlbBilling = new javax.swing.JLabel();
        jpnReporting = new javax.swing.JPanel();
        jlbReporting = new javax.swing.JLabel();
        jpnSupport = new javax.swing.JPanel();
        jlbSupport = new javax.swing.JLabel();
        jpnChangePassword = new javax.swing.JPanel();
        jlbChangePassword = new javax.swing.JLabel();
        jpnHomePage = new javax.swing.JPanel();
        jlbHomePage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jbtnLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jpnView.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jpnRoot.setLayout(new java.awt.GridBagLayout());

        jpnMenu.setBackground(new java.awt.Color(153, 153, 153));

        jpnMiniMart.setBackground(new java.awt.Color(153, 0, 51));

        jlbMinimart.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbMinimart.setForeground(new java.awt.Color(255, 255, 255));
        jlbMinimart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbMinimart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fpt/edu/lab/images/logoStore.png"))); // NOI18N
        jlbMinimart.setText("Mini Mart Management");

        javax.swing.GroupLayout jpnMiniMartLayout = new javax.swing.GroupLayout(jpnMiniMart);
        jpnMiniMart.setLayout(jpnMiniMartLayout);
        jpnMiniMartLayout.setHorizontalGroup(
            jpnMiniMartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnMiniMartLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbMinimart, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnMiniMartLayout.setVerticalGroup(
            jpnMiniMartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMiniMartLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbMinimart, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addComponent(jpnMiniMart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMiniMart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jpnRoot.add(jpnMenu, gridBagConstraints);

        jpnUser.setBackground(new java.awt.Color(0, 102, 0));
        jpnUser.setPreferredSize(new java.awt.Dimension(330, 60));

        jlbUser.setBackground(new java.awt.Color(255, 255, 255));
        jlbUser.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbUser.setForeground(new java.awt.Color(255, 255, 255));
        jlbUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fpt/edu/lab/images/logoUser.png"))); // NOI18N
        jlbUser.setText("User Management");

        javax.swing.GroupLayout jpnUserLayout = new javax.swing.GroupLayout(jpnUser);
        jpnUser.setLayout(jpnUserLayout);
        jpnUserLayout.setHorizontalGroup(
            jpnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbUser, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnUserLayout.setVerticalGroup(
            jpnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnUserLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 15);
        jpnRoot.add(jpnUser, gridBagConstraints);

        jpnProduct.setBackground(new java.awt.Color(0, 102, 0));
        jpnProduct.setPreferredSize(new java.awt.Dimension(330, 60));

        jlbProduct.setBackground(new java.awt.Color(255, 255, 255));
        jlbProduct.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbProduct.setForeground(new java.awt.Color(255, 255, 255));
        jlbProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fpt/edu/lab/images/logoProduct.png"))); // NOI18N
        jlbProduct.setText("Product Management");

        javax.swing.GroupLayout jpnProductLayout = new javax.swing.GroupLayout(jpnProduct);
        jpnProduct.setLayout(jpnProductLayout);
        jpnProductLayout.setHorizontalGroup(
            jpnProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnProductLayout.setVerticalGroup(
            jpnProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnProductLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbProduct)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 15);
        jpnRoot.add(jpnProduct, gridBagConstraints);

        jpnInventory.setBackground(new java.awt.Color(0, 102, 0));
        jpnInventory.setPreferredSize(new java.awt.Dimension(330, 60));

        jlbInventory.setBackground(new java.awt.Color(255, 255, 255));
        jlbInventory.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbInventory.setForeground(new java.awt.Color(255, 255, 255));
        jlbInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fpt/edu/lab/images/logoInventory.png"))); // NOI18N
        jlbInventory.setText("Inventory Management");

        javax.swing.GroupLayout jpnInventoryLayout = new javax.swing.GroupLayout(jpnInventory);
        jpnInventory.setLayout(jpnInventoryLayout);
        jpnInventoryLayout.setHorizontalGroup(
            jpnInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbInventory, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnInventoryLayout.setVerticalGroup(
            jpnInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInventoryLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbInventory)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 15);
        jpnRoot.add(jpnInventory, gridBagConstraints);

        jpnProductCategory.setBackground(new java.awt.Color(0, 102, 0));
        jpnProductCategory.setPreferredSize(new java.awt.Dimension(330, 60));

        jlbProductCategory.setBackground(new java.awt.Color(255, 255, 255));
        jlbProductCategory.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbProductCategory.setForeground(new java.awt.Color(255, 255, 255));
        jlbProductCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fpt/edu/lab/images/logoProductCategory.png"))); // NOI18N
        jlbProductCategory.setText("Category Management");

        javax.swing.GroupLayout jpnProductCategoryLayout = new javax.swing.GroupLayout(jpnProductCategory);
        jpnProductCategory.setLayout(jpnProductCategoryLayout);
        jpnProductCategoryLayout.setHorizontalGroup(
            jpnProductCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnProductCategoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbProductCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnProductCategoryLayout.setVerticalGroup(
            jpnProductCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnProductCategoryLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbProductCategory)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 15);
        jpnRoot.add(jpnProductCategory, gridBagConstraints);

        jpnBilling.setBackground(new java.awt.Color(0, 102, 0));
        jpnBilling.setPreferredSize(new java.awt.Dimension(330, 60));

        jlbBilling.setBackground(new java.awt.Color(255, 255, 255));
        jlbBilling.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbBilling.setForeground(new java.awt.Color(255, 255, 255));
        jlbBilling.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fpt/edu/lab/images/logoBilling.png"))); // NOI18N
        jlbBilling.setText("Billing");

        javax.swing.GroupLayout jpnBillingLayout = new javax.swing.GroupLayout(jpnBilling);
        jpnBilling.setLayout(jpnBillingLayout);
        jpnBillingLayout.setHorizontalGroup(
            jpnBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBillingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbBilling, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnBillingLayout.setVerticalGroup(
            jpnBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBillingLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbBilling)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 15);
        jpnRoot.add(jpnBilling, gridBagConstraints);

        jpnReporting.setBackground(new java.awt.Color(0, 102, 0));
        jpnReporting.setPreferredSize(new java.awt.Dimension(330, 60));

        jlbReporting.setBackground(new java.awt.Color(255, 255, 255));
        jlbReporting.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbReporting.setForeground(new java.awt.Color(255, 255, 255));
        jlbReporting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fpt/edu/lab/images/logoReport.png"))); // NOI18N
        jlbReporting.setText("Reporting");

        javax.swing.GroupLayout jpnReportingLayout = new javax.swing.GroupLayout(jpnReporting);
        jpnReporting.setLayout(jpnReportingLayout);
        jpnReportingLayout.setHorizontalGroup(
            jpnReportingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnReportingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbReporting, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnReportingLayout.setVerticalGroup(
            jpnReportingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnReportingLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbReporting)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 15);
        jpnRoot.add(jpnReporting, gridBagConstraints);

        jpnSupport.setBackground(new java.awt.Color(0, 102, 0));
        jpnSupport.setPreferredSize(new java.awt.Dimension(330, 60));

        jlbSupport.setBackground(new java.awt.Color(255, 255, 255));
        jlbSupport.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbSupport.setForeground(new java.awt.Color(255, 255, 255));
        jlbSupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fpt/edu/lab/images/logoSupport.png"))); // NOI18N
        jlbSupport.setText("Support");

        javax.swing.GroupLayout jpnSupportLayout = new javax.swing.GroupLayout(jpnSupport);
        jpnSupport.setLayout(jpnSupportLayout);
        jpnSupportLayout.setHorizontalGroup(
            jpnSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSupportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbSupport, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnSupportLayout.setVerticalGroup(
            jpnSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSupportLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbSupport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 15);
        jpnRoot.add(jpnSupport, gridBagConstraints);

        jpnChangePassword.setBackground(new java.awt.Color(0, 102, 0));
        jpnChangePassword.setPreferredSize(new java.awt.Dimension(330, 60));

        jlbChangePassword.setBackground(new java.awt.Color(255, 255, 255));
        jlbChangePassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbChangePassword.setForeground(new java.awt.Color(255, 255, 255));
        jlbChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fpt/edu/lab/images/logoChangePassword.png"))); // NOI18N
        jlbChangePassword.setText("Change Password");

        javax.swing.GroupLayout jpnChangePasswordLayout = new javax.swing.GroupLayout(jpnChangePassword);
        jpnChangePassword.setLayout(jpnChangePasswordLayout);
        jpnChangePasswordLayout.setHorizontalGroup(
            jpnChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnChangePasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnChangePasswordLayout.setVerticalGroup(
            jpnChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnChangePasswordLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbChangePassword)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 15);
        jpnRoot.add(jpnChangePassword, gridBagConstraints);

        jpnHomePage.setBackground(new java.awt.Color(0, 102, 0));
        jpnHomePage.setPreferredSize(new java.awt.Dimension(330, 60));

        jlbHomePage.setBackground(new java.awt.Color(255, 255, 255));
        jlbHomePage.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbHomePage.setForeground(new java.awt.Color(255, 255, 255));
        jlbHomePage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fpt/edu/lab/images/logoHome.png"))); // NOI18N
        jlbHomePage.setText("Home Page");

        javax.swing.GroupLayout jpnHomePageLayout = new javax.swing.GroupLayout(jpnHomePage);
        jpnHomePage.setLayout(jpnHomePageLayout);
        jpnHomePageLayout.setHorizontalGroup(
            jpnHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHomePageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbHomePage, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnHomePageLayout.setVerticalGroup(
            jpnHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHomePageLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbHomePage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 15);
        jpnRoot.add(jpnHomePage, gridBagConstraints);

        jbtnLogOut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnLogOut.setText("Log Out");
        jbtnLogOut.setPreferredSize(new java.awt.Dimension(130, 30));
        jbtnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogOutActionPerformed
        dispose();
        LoginJFrame login = new LoginJFrame();
        login.setVisible(true);
    }//GEN-LAST:event_jbtnLogOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnLogOut;
    private javax.swing.JLabel jlbBilling;
    private javax.swing.JLabel jlbChangePassword;
    private javax.swing.JLabel jlbHomePage;
    private javax.swing.JLabel jlbInventory;
    private javax.swing.JLabel jlbMinimart;
    private javax.swing.JLabel jlbProduct;
    private javax.swing.JLabel jlbProductCategory;
    private javax.swing.JLabel jlbReporting;
    private javax.swing.JLabel jlbSupport;
    private javax.swing.JLabel jlbUser;
    private javax.swing.JPanel jpnBilling;
    private javax.swing.JPanel jpnChangePassword;
    private javax.swing.JPanel jpnHomePage;
    private javax.swing.JPanel jpnInventory;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnMiniMart;
    private javax.swing.JPanel jpnProduct;
    private javax.swing.JPanel jpnProductCategory;
    private javax.swing.JPanel jpnReporting;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnSupport;
    private javax.swing.JPanel jpnUser;
    private javax.swing.JPanel jpnView;
    // End of variables declaration//GEN-END:variables
}
