/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fpt.edu.lab.view;

import fpt.edu.lab.dao.CategoryDao;
import fpt.edu.lab.model.Category;
import java.util.ArrayList;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Hi
 */
public class ProductCategoryJPanel extends javax.swing.JPanel {

    DefaultTableModel model;
    ArrayList<Category> list;
    Category c;
    ResourceBundle bundle;

    /**
     * Creates new form ProjuctCategoryJPanel
     */
    public ProductCategoryJPanel(ResourceBundle bundle) {
        initComponents();
        this.bundle = bundle;
        model = (DefaultTableModel) jtbMain.getModel();
        list = new ArrayList<>();
        c = new Category();
        addColumnTable();
        setSizeColumn();
        setUpUILanguage(bundle);
        list = CategoryDao.getAllCategory();
        loadCategoryTable(list);
    }

    public void setSizeColumn() {
        TableColumnModel columnModel = jtbMain.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(125);
        jtbMain.setRowHeight(30);
        columnModel.getColumn(1).setPreferredWidth(327);

    }

    public void setUpUILanguage(ResourceBundle bundle) {
        jPanel2.setBorder(BorderFactory.createTitledBorder(bundle.getString("jpnListCategory")));
        jPanel3.setBorder(BorderFactory.createTitledBorder(bundle.getString("jpnInforCategory")));
        lbName.setText(bundle.getString("jlbName"));
        jbtnAdd.setText(bundle.getString("jbtnAdd"));
        jbtnUpdate.setText(bundle.getString("jbtnUpdate"));
        jbtnDelete.setText(bundle.getString("jbtnDelete"));
    }

    public void addColumnTable() {
        model.addColumn(bundle.getString("CategoryCode"));
        model.addColumn(bundle.getString("CategoryName"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbMain = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jbtnUpdate = new javax.swing.JButton();
        jbtnAdd = new javax.swing.JButton();
        lbName = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jbtnDelete = new javax.swing.JButton();
        jtfId = new javax.swing.JTextField();
        lbName1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbMain1 = new javax.swing.JTable();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List Category", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jtbMain.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtbMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtbMain.setPreferredSize(new java.awt.Dimension(0, 500));
        jtbMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbMainMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbMain);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jbtnUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });

        jbtnAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnAdd.setText("Add");
        jbtnAdd.setPreferredSize(new java.awt.Dimension(70, 30));
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });

        lbName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbName.setText("Name:");

        jtfName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jbtnDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        jtfId.setEditable(false);
        jtfId.setBackground(new java.awt.Color(204, 204, 204));
        jtfId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbName1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbName1.setText("ID:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbName, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(lbName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfId)
                            .addComponent(jtfName)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jbtnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                        .addGap(40, 40, 40)
                        .addComponent(jbtnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                        .addGap(40, 40, 40)
                        .addComponent(jbtnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnUpdate)
                    .addComponent(jbtnDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbtnAdd, jbtnDelete, jbtnUpdate});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jtbMain1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane3.setViewportView(jtbMain1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtbMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbMainMouseClicked
        if (jtbMain.getSelectedRow() != -1) {
            jtfId.setText(model.getValueAt(jtbMain.getSelectedRow(), 0).toString());
            jtfName.setText(model.getValueAt(jtbMain.getSelectedRow(), 1).toString());
        }
    }//GEN-LAST:event_jtbMainMouseClicked

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        int id = Integer.parseInt(jtfId.getText().toString());
        CategoryDao.deleteCategory(id);
        list = CategoryDao.getAllCategory();
        loadCategoryTable(list);
        if (!list.isEmpty()) {
            jtfId.setText(list.get(0).getCategoryId() + "");
            jtfName.setText(list.get(0).getCategoryName());
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        int id = c.getCategoryId();
        String CategoryName = jtfName.getText();
        if (CategoryName.equals("")) {
            JOptionPane.showMessageDialog(this, bundle.getString("joCategoryName"));
            return;
        }
        Category c = new Category(id, CategoryName);
        CategoryDao.addCategory(c);
        list = CategoryDao.getAllCategory();
        loadCategoryTable(list);
    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        int id = Integer.parseInt(jtfId.getText().toString());
        String CategoryName = jtfName.getText();
        if (CategoryName.equals("")) {
            JOptionPane.showMessageDialog(this, bundle.getString("joCategoryName"));
            return;
        }
        Category c = new Category(id, CategoryName);
        CategoryDao.updateCategory(id, c);
        list = CategoryDao.getAllCategory();
        loadCategoryTable(list);
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    public void loadCategoryTable(ArrayList<Category> list) {
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        for (Category c : list) {
            model.addRow(new Object[]{c.getCategoryId(), c.getCategoryName()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JTable jtbMain;
    private javax.swing.JTable jtbMain1;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfName;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbName1;
    // End of variables declaration//GEN-END:variables
}
