/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fpt.edu.lab.view;

import fpt.edu.lab.dao.RoleDao;
import fpt.edu.lab.dao.UserDao;
import fpt.edu.lab.model.Role;
import fpt.edu.lab.model.User;
import java.util.ArrayList;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Hi
 */
public class UserJPanel extends javax.swing.JPanel {

    ArrayList<User> listUser = new ArrayList<>();
    ArrayList<Role> listRole = new ArrayList<>();
    ResourceBundle bundle;
    DefaultTableModel model;

    /**
     * Creates new form UserJPanel
     *
     * @param bundle
     */
    public UserJPanel(ResourceBundle bundle) {
        initComponents();
        model = (DefaultTableModel) tableListUser.getModel();
        this.bundle = bundle;
        addColumnTable();
        loadToUserTable();
        setUpUILanguage(bundle);
        getRoleName();
        setHeightColumn();
    }

    public void setHeightColumn() {
        TableColumnModel columnModel = tableListUser.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(70);
        columnModel.getColumn(1).setPreferredWidth(155);
        columnModel.getColumn(2).setPreferredWidth(70);
        columnModel.getColumn(3).setPreferredWidth(70);
        tableListUser.setRowHeight(30);

    }

    public void setUpUILanguage(ResourceBundle bundle) {
        labelUsername.setText(bundle.getString("jlbUserName"));
        labelPassword.setText(bundle.getString("jlbPassword"));
        labelFullname.setText(bundle.getString("jlbFullName"));
        labelRoleName.setText(bundle.getString("jlbRoleName"));
        btnUserNew.setText(bundle.getString("jbtnAdd"));
        btnUserUpdate.setText(bundle.getString("jbtnUpdate"));
        btnUserDelete.setText(bundle.getString("jbtnDelete"));
        labelFullNameSearch.setText(bundle.getString("jlbFullName"));
        labelRoleNameSearch.setText(bundle.getString("jlbRoleName"));
        btnSearch.setText(bundle.getString("jbtnSearch"));
        jScrollPane1.setBorder(BorderFactory.createTitledBorder(bundle.getString("jtbListUser")));
        panelInfor.setBorder(BorderFactory.createTitledBorder(bundle.getString("jpnInforUser")));
        panelSearch.setBorder(BorderFactory.createTitledBorder(bundle.getString("jpnSearchUser")));
    }

    public void addColumnTable() {
        model.addColumn(bundle.getString("jlbUserName"));
        model.addColumn(bundle.getString("jlbFullName"));
        model.addColumn(bundle.getString("jlbPassword"));
        model.addColumn(bundle.getString("jlbRoleName"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jpnUserMain = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListUser = new javax.swing.JTable();
        panelInfor = new javax.swing.JPanel();
        txtFullname = new javax.swing.JTextField();
        btnUserDelete = new javax.swing.JButton();
        labelUsername = new javax.swing.JLabel();
        btnUserNew = new javax.swing.JButton();
        labelPassword = new javax.swing.JLabel();
        labelFullname = new javax.swing.JLabel();
        btnUserUpdate = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        cbRole = new javax.swing.JComboBox<>();
        labelRoleName = new javax.swing.JLabel();
        panelSearch = new javax.swing.JPanel();
        labelRoleNameSearch = new javax.swing.JLabel();
        labelFullNameSearch = new javax.swing.JLabel();
        cbRolename = new javax.swing.JComboBox<>();
        txtSearchFullname = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jpnUserMain.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List user", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        tableListUser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        tableListUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableListUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableListUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableListUser);

        panelInfor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information user", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        txtFullname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFullname.setPreferredSize(new java.awt.Dimension(6, 30));

        btnUserDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUserDelete.setText("Delete");
        btnUserDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserDeleteActionPerformed(evt);
            }
        });

        labelUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelUsername.setText("Username");

        btnUserNew.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUserNew.setText("New");
        btnUserNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserNewActionPerformed(evt);
            }
        });

        labelPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPassword.setText("Password");

        labelFullname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelFullname.setText("Full Name");

        btnUserUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUserUpdate.setText("Update");
        btnUserUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserUpdateActionPerformed(evt);
            }
        });

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsername.setPreferredSize(new java.awt.Dimension(6, 30));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPassword.setPreferredSize(new java.awt.Dimension(6, 30));

        cbRole.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        labelRoleName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelRoleName.setText("Role Name");

        javax.swing.GroupLayout panelInforLayout = new javax.swing.GroupLayout(panelInfor);
        panelInfor.setLayout(panelInforLayout);
        panelInforLayout.setHorizontalGroup(
            panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInforLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInforLayout.createSequentialGroup()
                        .addGroup(panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelFullname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelRoleName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFullname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(panelInforLayout.createSequentialGroup()
                        .addComponent(btnUserNew, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                        .addGap(25, 25, 25)
                        .addComponent(btnUserUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addGap(28, 28, 28)
                        .addComponent(btnUserDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))))
        );
        panelInforLayout.setVerticalGroup(
            panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInforLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFullname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelFullname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRoleName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUserNew, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search user", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        panelSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        labelRoleNameSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelRoleNameSearch.setText("Rolename");

        labelFullNameSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelFullNameSearch.setText("Full Name");

        cbRolename.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbRolename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRolenameActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setPreferredSize(new java.awt.Dimension(75, 30));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelSearchLayout.createSequentialGroup()
                        .addComponent(labelRoleNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbRolename, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSearchLayout.createSequentialGroup()
                        .addComponent(labelFullNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchFullname)))
                .addGap(51, 51, 51)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFullNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbRolename, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRoleNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnUserMainLayout = new javax.swing.GroupLayout(jpnUserMain);
        jpnUserMain.setLayout(jpnUserMainLayout);
        jpnUserMainLayout.setHorizontalGroup(
            jpnUserMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnUserMainLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInfor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnUserMainLayout.setVerticalGroup(
            jpnUserMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnUserMainLayout.createSequentialGroup()
                .addGroup(jpnUserMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(panelInfor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnUserMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnUserMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserNewActionPerformed
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        String fullname = txtFullname.getText();
        int indexRoleSelect = cbRole.getSelectedIndex();
        String rolename = listRole.get(indexRoleSelect).getRoleName();
        if (username.equals("") || password.equals("") || fullname.equals("")) {
            JOptionPane.showMessageDialog(getRootPane(), bundle.getString("joFillIn"));
        } else if (UserDao.isDuplicate(username)) {
            JOptionPane.showMessageDialog(getRootPane(), bundle.getString("joCheckExistUser"));
        } else {
            User user = new User(username, fullname, password, rolename);
            UserDao.addUser(user, indexRoleSelect);
            loadToUserTable();
        }
    }//GEN-LAST:event_btnUserNewActionPerformed

    private void btnUserUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserUpdateActionPerformed
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        String fullname = txtFullname.getText();
        String rolename = String.valueOf(cbRole.getSelectedIndex() + 1);
        User user = new User(username, fullname, password, rolename);
        UserDao.updateUser(username, user);
        loadToUserTable();
    }//GEN-LAST:event_btnUserUpdateActionPerformed

    private void btnUserDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserDeleteActionPerformed
        String username = txtUsername.getText();
        UserDao.deleteUser(username);
        loadToUserTable();
    }//GEN-LAST:event_btnUserDeleteActionPerformed

    private void tableListUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListUserMouseClicked
        DefaultTableModel tableModel = (DefaultTableModel) this.tableListUser.getModel();
        txtUsername.setText(tableModel.getValueAt(tableListUser.getSelectedRow(), 0).toString());
        txtFullname.setText(tableModel.getValueAt(tableListUser.getSelectedRow(), 1).toString());
        txtPassword.setText(tableModel.getValueAt(tableListUser.getSelectedRow(), 2).toString());
        cbRole.setSelectedIndex(getIndexRole(tableModel.getValueAt(tableListUser.getSelectedRow(), 3).toString()));
    }//GEN-LAST:event_tableListUserMouseClicked

    private void cbRolenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRolenameActionPerformed

    }//GEN-LAST:event_cbRolenameActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) this.tableListUser.getModel();
        ArrayList<User> list = null;
        list = UserDao.search(txtSearchFullname.getText(), cbRolename.getSelectedItem().toString());
        while (tableModel.getRowCount() > 0) {
            tableModel.removeRow(0);
        }
        for (User user : list) {
            tableModel.addRow(new Object[]{user.getUsername(), user.getFullname(), user.getPassword(), user.getRolename()});
        }
    }//GEN-LAST:event_btnSearchActionPerformed
    public void loadToUserTable() {
        DefaultTableModel tableModel = (DefaultTableModel) this.tableListUser.getModel();
        while (tableModel.getRowCount() > 0) {
            tableModel.removeRow(0);
        }

        listUser = UserDao.getAllUser();
        for (User user : listUser) {
            tableModel.addRow(new Object[]{user.getUsername(), user.getFullname(), user.getPassword(), user.getRolename()});
        }
    }

    public int getIndexRole(String rolename) {
        int pos = -1;
        for (int i = 0; i < listRole.size(); i++) {
            if (listRole.get(i).getRoleName().equalsIgnoreCase(rolename)) {
                return i;
            }
        }
        return pos;
    }

    public void getRoleName() {
        listRole = RoleDao.getAllRole();
        for (Role role : listRole) {
            cbRole.addItem(role.getRoleName());
            cbRolename.addItem(role.getRoleName());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUserDelete;
    private javax.swing.JButton btnUserNew;
    private javax.swing.JButton btnUserUpdate;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JComboBox<String> cbRolename;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnUserMain;
    private javax.swing.JLabel labelFullNameSearch;
    private javax.swing.JLabel labelFullname;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelRoleName;
    private javax.swing.JLabel labelRoleNameSearch;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPanel panelInfor;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JTable tableListUser;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtSearchFullname;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
