/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fpt.edu.lab.view;

import fpt.edu.lab.dao.ProductDao;
import fpt.edu.lab.model.BillDetails;
import java.util.ArrayList;
import java.util.ResourceBundle;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguye
 */
public class ViewBillDetailsJPanel extends javax.swing.JFrame {
    
    DefaultTableModel billDetailsTableModel;
    ResourceBundle bundle;

    /**
     * Creates new form ViewBillDetails
     *
     * @param listBillDetailses
     */
    public ViewBillDetailsJPanel(ArrayList<BillDetails> listBillDetailses,ResourceBundle bundle) {
        initComponents();
        this.bundle = bundle;
        billDetailsTableModel = (DefaultTableModel) jtbViewBillDetails.getModel();
        addColumnTable();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        double totalPrice = 0;
        for (BillDetails bd : listBillDetailses) {
            billDetailsTableModel.addRow(new Object[]{
                bd.getBill_id(), bd.getBill_detail_id(), bd.getProduct_code(), ProductDao.getProductName(bd.getProduct_code()),
                bd.getPrice(), bd.getQuantity()
            });
            totalPrice += bd.getPrice();
        }
        jlbTotalPrice.setText(bundle.getString("jlbTotalPrice") + ": " + totalPrice);
        setUpUILanguage();
    }
    
      public void setUpUILanguage() {
         jbtnExit.setText(bundle.getString("jbtnExit"));
    }
    public void addColumnTable() {
        billDetailsTableModel.addColumn(bundle.getString("BillID"));
        billDetailsTableModel.addColumn(bundle.getString("BillDetailsId"));
        billDetailsTableModel.addColumn(bundle.getString("ProductCode"));
        billDetailsTableModel.addColumn(bundle.getString("ProductName"));
        billDetailsTableModel.addColumn(bundle.getString("Price"));
        billDetailsTableModel.addColumn(bundle.getString("Quantity"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbViewBillDetails = new javax.swing.JTable();
        jlbTotalPrice = new javax.swing.JLabel();
        jbtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bill Details");

        jtbViewBillDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtbViewBillDetails);

        jlbTotalPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbTotalPrice.setText("Total Price: ");
        jlbTotalPrice.setPreferredSize(new java.awt.Dimension(72, 30));

        jbtnExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.setPreferredSize(new java.awt.Dimension(55, 30));
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnExitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JLabel jlbTotalPrice;
    private javax.swing.JTable jtbViewBillDetails;
    // End of variables declaration//GEN-END:variables
}
