/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fpt.edu.lab.view;

import fpt.edu.lab.dao.ProductDao;
import fpt.edu.lab.model.BillDetails;
import fpt.edu.lab.model.StockDetails;
import java.util.ArrayList;
import java.util.ResourceBundle;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguye
 */
public class ViewStockDetailsJPanel extends javax.swing.JFrame {

    ResourceBundle bundle;
    DefaultTableModel stockDetailsTableModel;

    /**
     * Creates new form ViewBillDetails
     *
     * @param listBillDetailses
     */
    public ViewStockDetailsJPanel(ArrayList<StockDetails> listStockDetailses, ResourceBundle bundle) {
        initComponents();
        this.bundle = bundle;
        stockDetailsTableModel = (DefaultTableModel) jtbViewStockDetails.getModel();
        addColumnTable();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        for (StockDetails sd : listStockDetailses) {
            stockDetailsTableModel.addRow(new Object[]{
                sd.getStockId(), sd.getStockDetailsId(), sd.getProductCode(), sd.getQuantity()
            });
        }
        setUpUILanguage();
    }

    public void setUpUILanguage() {
        jbtnExit.setText(bundle.getString("jbtnExit"));
    }

    public void addColumnTable() {
        stockDetailsTableModel.addColumn(bundle.getString("StockID"));
        stockDetailsTableModel.addColumn(bundle.getString("StockDetailsId"));
        stockDetailsTableModel.addColumn(bundle.getString("ProductCode"));
        stockDetailsTableModel.addColumn(bundle.getString("Quantity"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbViewStockDetails = new javax.swing.JTable();
        jbtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stock Details");

        jtbViewStockDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtbViewStockDetails);

        jbtnExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.setPreferredSize(new java.awt.Dimension(55, 30));
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnExitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JTable jtbViewStockDetails;
    // End of variables declaration//GEN-END:variables
}
